name: Update Readme

on:
  schedule: # Run workflow automatically
    - cron: '30 5 * * *' # Runs every morning at 05:30 am
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme:
    name: Update this repo's README with latest activities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Updating recent GitHub activity'